compiler1 = gcc

collatz:
	$(compiler1) -o Collatz_saurabh Collatz_saurabh.c
	$(compiler1) -o collatz_r collatz_recursive_saurabh.c

clean:
	rm Collatz_saurabh
	rm collatz_r
	rm results_Childpid_Parentpid.dat
